import { User, Project, Lead, Announcement, LeadStatus } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "USR-001",
    name: "Vikram Casagrand",
    role: "Builder Admin",
    phone: "+91 98765 43210",
    email: "vikram@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-002",
    name: "Suresh Kumar",
    role: "Manager",
    phone: "+91 98765 43211",
    email: "suresh.k@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-003",
    name: "Pooja Hegde",
    role: "Receptionist",
    phone: "+91 98765 43212",
    email: "pooja.h@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-004",
    name: "Amit Sharma",
    role: "Sales Executive",
    phone: "+91 98765 43213",
    email: "amit.s@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-005",
    name: "Rohan Das",
    role: "Sales Executive",
    phone: "+91 98765 43214",
    email: "rohan.d@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-006",
    name: "Meera Krishnan",
    role: "CRM",
    phone: "+91 98765 43215",
    email: "meera.k@casagrand.co.in",
    status: "Active"
  },
  {
    id: "USR-007",
    name: "Ramesh Patel",
    role: "CP Admin",
    phone: "+91 98765 43216",
    email: "ramesh@apexrealty.com",
    status: "Active",
    agency: "Apex Realty",
    earnings: 4500000
  },
  {
    id: "USR-008",
    name: "Karan Johar",
    role: "FoS",
    phone: "+91 98765 43217",
    email: "karan@apexrealty.com",
    status: "Active",
    agency: "Apex Realty"
  },
  {
    id: "USR-009",
    name: "Varun Dhawan",
    role: "FoS",
    phone: "+91 98765 43218",
    email: "varun@apexrealty.com",
    status: "Active",
    agency: "Apex Realty"
  }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "PRJ-001",
    name: "Casagrand Zenith",
    location: "Medavakkam, Chennai",
    priceRange: "₹65 Lakhs - ₹1.2 Crores",
    type: "2 & 3 BHK Luxury Apartments",
    unitsAvailable: 45,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=60"
  },
  {
    id: "PRJ-002",
    name: "Casagrand Utopia",
    location: "Manapakkam, Chennai",
    priceRange: "₹48 Lakhs - ₹95 Lakhs",
    type: "1, 2 & 3 BHK Kids-Themed Community",
    unitsAvailable: 62,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=60"
  },
  {
    id: "PRJ-003",
    name: "Casagrand Tudor",
    location: "Mogappair, Chennai",
    priceRange: "₹85 Lakhs - ₹1.8 Crores",
    type: "2, 3 & 4 BHK Wellness Homes",
    unitsAvailable: 28,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=60"
  },
  {
    id: "PRJ-004",
    name: "Casagrand First City",
    location: "Sholinganallur, Chennai",
    priceRange: "₹55 Lakhs - ₹1.1 Crores",
    type: "2, 3 & 4 BHK Smart Homes",
    unitsAvailable: 74,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&auto=format&fit=crop&q=60"
  },
  {
    id: "PRJ-005",
    name: "Casagrand Esmeralda",
    location: "Sarjapur, Bangalore",
    priceRange: "₹1.5 Crores - ₹3.2 Crores",
    type: "3 & 4 BHK Premium Villas",
    unitsAvailable: 15,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=60"
  }
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ANN-001",
    title: "Double Commission Bonanza!",
    content: "Earn an extra 1.0% brokerage on all bookings made in Casagrand Zenith from 15th to 20th July. Applicable for all CP partners.",
    date: "2026-07-14"
  },
  {
    id: "ANN-002",
    title: "Casagrand Esmeralda Project Training",
    content: "Detailed walkthrough and virtual model tour scheduled for 18th July at 4:00 PM. Highly recommended for all FoS team members.",
    date: "2026-07-13"
  },
  {
    id: "ANN-003",
    title: "New Lead Submission Incentive",
    content: "Every validated lead created by FoS which converts to a site visit within 7 days gets ₹1,500 direct spot bonus.",
    date: "2026-07-10"
  }
];

// Helper to generate a historical timeline for a lead
const makeHistory = (statusList: LeadStatus[]): any[] => {
  return statusList.map((st, idx) => {
    const hoursAgo = (statusList.length - idx) * 24;
    const date = new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString().split('T')[0];
    return {
      id: `H-${Math.random().toString(36).substr(2, 5)}`,
      status: st,
      updatedAt: date,
      updatedBy: idx === 0 
        ? "FoS - Karan Johar" 
        : idx < 3 
          ? "Receptionist - Pooja Hegde" 
          : idx < 6 
            ? "Sales Executive - Amit Sharma" 
            : "CRM - Meera Krishnan",
      notes: `Lead transition to status ${st}`
    };
  });
};

export const MOCK_LEADS: Lead[] = [
  // Status 1: Lead Created
  {
    id: "CG-1001",
    name: "Aditya Roy",
    phone: "9123456781",
    email: "aditya.roy@gmail.com",
    status: "Lead Created",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-15",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: null,
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created"])
  },
  {
    id: "CG-1002",
    name: "Deepika Padukone",
    phone: "9123456782",
    email: "deepika.p@gmail.com",
    status: "Lead Created",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-14",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: null,
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created"])
  },
  {
    id: "CG-1003",
    name: "Ranbir Kapoor",
    phone: "9123456783",
    email: "ranbir.k@gmail.com",
    status: "Lead Created",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-15",
    createdBy: "Ramesh Patel",
    createdByRole: "CP Admin",
    claimedBy: null,
    claimedById: null,
    leadQuality: null,
    project: "Casagrand Tudor",
    history: makeHistory(["Lead Created"])
  },
  
  // Status 2: Waiting For Visit
  {
    id: "CG-1004",
    name: "Alia Bhatt",
    phone: "9123456784",
    email: "alia.bhatt@yahoo.com",
    status: "Waiting For Visit",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-12",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Warm",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit"])
  },
  {
    id: "CG-1005",
    name: "Siddharth Malhotra",
    phone: "9123456785",
    email: "sid.m@hotmail.com",
    status: "Waiting For Visit",
    statusUpdatedDate: "2026-07-13",
    createdDate: "2026-07-11",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Cold",
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created", "Waiting For Visit"])
  },

  // Status 3: Visit Confirmed
  {
    id: "CG-1006",
    name: "Katrina Kaif",
    phone: "9123456786",
    email: "katrina.k@gmail.com",
    status: "Visit Confirmed",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-12",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed"])
  },
  {
    id: "CG-1007",
    name: "Vicky Kaushal",
    phone: "9123456787",
    email: "vicky.k@gmail.com",
    status: "Visit Confirmed",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-12",
    createdBy: "Pooja Hegde",
    createdByRole: "Receptionist",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Warm",
    project: "Casagrand Tudor",
    history: makeHistory(["Lead Created", "Visit Confirmed"])
  },

  // Status 4: Assigned To Sales Executive
  {
    id: "CG-1008",
    name: "Ranveer Singh",
    phone: "9123456788",
    email: "ranveer.s@gmail.com",
    status: "Assigned To Sales Executive",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-12",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive"])
  },
  {
    id: "CG-1009",
    name: "Kriti Sanon",
    phone: "9123456789",
    email: "kriti.s@gmail.com",
    status: "Assigned To Sales Executive",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-11",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Warm",
    project: "Casagrand First City",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive"])
  },
  {
    id: "CG-1010",
    name: "Kartik Aaryan",
    phone: "9123456790",
    email: "kartik.a@gmail.com",
    status: "Assigned To Sales Executive",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-12",
    createdBy: "Pooja Hegde",
    createdByRole: "Receptionist",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Cold",
    project: "Casagrand Esmeralda",
    history: makeHistory(["Lead Created", "Visit Confirmed", "Assigned To Sales Executive"])
  },

  // Status 5: Site Visit Done
  {
    id: "CG-1011",
    name: "Sara Ali Khan",
    phone: "9123456791",
    email: "sara.a@gmail.com",
    status: "Site Visit Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-10",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done"])
  },
  {
    id: "CG-1012",
    name: "Janhvi Kapoor",
    phone: "9123456792",
    email: "janhvi.k@gmail.com",
    status: "Site Visit Done",
    statusUpdatedDate: "2026-07-13",
    createdDate: "2026-07-09",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Warm",
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done"])
  },

  // Status 6: Token Done
  {
    id: "CG-1013",
    name: "Tiger Shroff",
    phone: "9123456793",
    email: "tiger.s@gmail.com",
    status: "Token Done",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-08",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block A - 402",
    paymentReceived: 100000,
    paymentPending: 400000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done"])
  },
  {
    id: "CG-1014",
    name: "Kiara Advani",
    phone: "9123456794",
    email: "kiara.a@gmail.com",
    status: "Token Done",
    statusUpdatedDate: "2026-07-13",
    createdDate: "2026-07-07",
    createdBy: "Ramesh Patel",
    createdByRole: "CP Admin",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Esmeralda",
    unitDetails: "Villa 12",
    paymentReceived: 500000,
    paymentPending: 2500000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done"])
  },

  // Status 7: Booking Done
  {
    id: "CG-1015",
    name: "Rajkummar Rao",
    phone: "9123456795",
    email: "rajkumar.r@gmail.com",
    status: "Booking Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-05",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Tudor",
    unitDetails: "Block C - 105",
    paymentReceived: 1500000,
    paymentPending: 500000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done"])
  },
  {
    id: "CG-1016",
    name: "Ayushmann Khurrana",
    phone: "9123456796",
    email: "ayushmann.k@gmail.com",
    status: "Booking Done",
    statusUpdatedDate: "2026-07-12",
    createdDate: "2026-07-04",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand First City",
    unitDetails: "Block B - 908",
    paymentReceived: 1000000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done"])
  },

  // Status 8: Agreement Pending
  {
    id: "CG-1017",
    name: "Varun Tej",
    phone: "9123456797",
    email: "varun.t@gmail.com",
    status: "Agreement Pending",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-01",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block A - 501",
    paymentReceived: 1200000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending"])
  },

  // Status 9: Agreement Done
  {
    id: "CG-1018",
    name: "Rashmika Mandanna",
    phone: "9123456798",
    email: "rashmika.m@gmail.com",
    status: "Agreement Done",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-06-28",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Utopia",
    unitDetails: "Block D - 203",
    paymentReceived: 2000000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done"])
  },

  // Status 10: Brokerage Pending
  {
    id: "CG-1019",
    name: "Vijay Deverakonda",
    phone: "9123456799",
    email: "vijay.d@gmail.com",
    status: "Brokerage Pending",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-06-25",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand First City",
    unitDetails: "Block A - 1004",
    paymentReceived: 2500000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done", "Brokerage Pending"])
  },

  // Status 11: Brokerage Released
  {
    id: "CG-1020",
    name: "Allu Arjun",
    phone: "9123456800",
    email: "allu.arjun@gmail.com",
    status: "Brokerage Released",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-06-20",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block B - 302",
    paymentReceived: 3000000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done", "Brokerage Pending", "Brokerage Released"])
  },

  // Status 12: Completed
  {
    id: "CG-1021",
    name: "Mahesh Babu",
    phone: "9123456801",
    email: "mahesh.b@gmail.com",
    status: "Completed",
    statusUpdatedDate: "2026-07-12",
    createdDate: "2026-06-15",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Tudor",
    unitDetails: "Block A - 102",
    paymentReceived: 4500000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done", "Brokerage Pending", "Brokerage Released", "Completed"])
  },

  // Status Not Interested
  {
    id: "CG-1022",
    name: "Sanjay Dutt",
    phone: "9123456802",
    email: "sanjay.d@yahoo.com",
    status: "Not Interested",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-10",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Cold",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Not Interested"])
  },

  // Rest of the 18 leads to reach 40 leads, properly mixed
  {
    id: "CG-1023",
    name: "Anil Kapoor",
    phone: "9123456803",
    email: "anil.k@gmail.com",
    status: "Waiting For Visit",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-14",
    createdBy: "Ramesh Patel",
    createdByRole: "CP Admin",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Warm",
    project: "Casagrand Esmeralda",
    history: makeHistory(["Lead Created", "Waiting For Visit"])
  },
  {
    id: "CG-1024",
    name: "Madhuri Dixit",
    phone: "9123456804",
    email: "madhuri.d@gmail.com",
    status: "Visit Confirmed",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-13",
    createdBy: "Pooja Hegde",
    createdByRole: "Receptionist",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Hot",
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created", "Visit Confirmed"])
  },
  {
    id: "CG-1025",
    name: "Aishwarya Rai",
    phone: "9123456805",
    email: "aishwarya.r@gmail.com",
    status: "Assigned To Sales Executive",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-14",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Warm",
    project: "Casagrand First City",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive"])
  },
  {
    id: "CG-1026",
    name: "Abhishek Bachchan",
    phone: "9123456806",
    email: "abhishek.b@gmail.com",
    status: "Site Visit Done",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-10",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Warm",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done"])
  },
  {
    id: "CG-1027",
    name: "Saif Ali Khan",
    phone: "9123456807",
    email: "saif.ak@gmail.com",
    status: "Token Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-09",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Tudor",
    unitDetails: "Block B - 204",
    paymentReceived: 200000,
    paymentPending: 800000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done"])
  },
  {
    id: "CG-1028",
    name: "Kareena Kapoor",
    phone: "9123456808",
    email: "kareena.k@gmail.com",
    status: "Booking Done",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-05",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block A - 1102",
    paymentReceived: 1200000,
    paymentPending: 200000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done"])
  },
  {
    id: "CG-1029",
    name: "Hrithik Roshan",
    phone: "9123456809",
    email: "hrithik.r@gmail.com",
    status: "Not Interested",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-12",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Cold",
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Not Interested"])
  },
  {
    id: "CG-1030",
    name: "Preity Zinta",
    phone: "9123456810",
    email: "preity.z@gmail.com",
    status: "Lead Created",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-15",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: null,
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created"])
  },
  {
    id: "CG-1031",
    name: "Juhi Chawla",
    phone: "9123456811",
    email: "juhi.c@gmail.com",
    status: "Waiting For Visit",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-12",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Warm",
    project: "Casagrand Tudor",
    history: makeHistory(["Lead Created", "Waiting For Visit"])
  },
  {
    id: "CG-1032",
    name: "Raveena Tandon",
    phone: "9123456812",
    email: "raveena.t@gmail.com",
    status: "Visit Confirmed",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-14",
    createdBy: "Pooja Hegde",
    createdByRole: "Receptionist",
    claimedBy: null,
    claimedById: null,
    leadQuality: "Warm",
    project: "Casagrand Utopia",
    history: makeHistory(["Lead Created", "Visit Confirmed"])
  },
  {
    id: "CG-1033",
    name: "Sunny Deol",
    phone: "9123456813",
    email: "sunny.d@gmail.com",
    status: "Assigned To Sales Executive",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-13",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand First City",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive"])
  },
  {
    id: "CG-1034",
    name: "Bobby Deol",
    phone: "9123456814",
    email: "bobby.d@gmail.com",
    status: "Site Visit Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-11",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done"])
  },
  {
    id: "CG-1035",
    name: "Jackie Shroff",
    phone: "9123456815",
    email: "jackie.s@gmail.com",
    status: "Token Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-08",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Warm",
    project: "Casagrand Esmeralda",
    unitDetails: "Villa 3",
    paymentReceived: 300000,
    paymentPending: 1700000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done"])
  },
  {
    id: "CG-1036",
    name: "Suniel Shetty",
    phone: "9123456816",
    email: "suniel.s@gmail.com",
    status: "Booking Done",
    statusUpdatedDate: "2026-07-14",
    createdDate: "2026-07-06",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Utopia",
    unitDetails: "Block E - 104",
    paymentReceived: 1000000,
    paymentPending: 100000,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done"])
  },
  {
    id: "CG-1037",
    name: "Akshay Kumar",
    phone: "9123456817",
    email: "akshay.k@gmail.com",
    status: "Agreement Pending",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-07-03",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block C - 302",
    paymentReceived: 1800000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending"])
  },
  {
    id: "CG-1038",
    name: "Kajol Devgan",
    phone: "9123456818",
    email: "kajol.d@gmail.com",
    status: "Agreement Done",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-06-30",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand Tudor",
    unitDetails: "Block B - 401",
    paymentReceived: 2100000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done"])
  },
  {
    id: "CG-1039",
    name: "Ajay Devgan",
    phone: "9123456819",
    email: "ajay.d@gmail.com",
    status: "Brokerage Pending",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-06-25",
    createdBy: "Karan Johar",
    createdByRole: "FoS",
    claimedBy: "Amit Sharma",
    claimedById: "USR-004",
    leadQuality: "Hot",
    project: "Casagrand Zenith",
    unitDetails: "Block A - 702",
    paymentReceived: 3200000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done", "Brokerage Pending"])
  },
  {
    id: "CG-1040",
    name: "Karisma Kapoor",
    phone: "9123456820",
    email: "karisma.k@gmail.com",
    status: "Brokerage Released",
    statusUpdatedDate: "2026-07-15",
    createdDate: "2026-06-22",
    createdBy: "Varun Dhawan",
    createdByRole: "FoS",
    claimedBy: "Rohan Das",
    claimedById: "USR-005",
    leadQuality: "Hot",
    project: "Casagrand First City",
    unitDetails: "Block D - 501",
    paymentReceived: 2900000,
    paymentPending: 0,
    history: makeHistory(["Lead Created", "Waiting For Visit", "Visit Confirmed", "Assigned To Sales Executive", "Site Visit Done", "Token Done", "Booking Done", "Agreement Pending", "Agreement Done", "Brokerage Pending", "Brokerage Released"])
  }
];
